---
# defaults file for jpaybar.Apache2

vhost:
  ip:
  #listen:
    #- http: 80
    #- https: 443
  serverName: 
  documentRoot: 
  certLocation: 
  certKeyLocation: 

install_packages:
  #- httpd
  #- mod_ssl
  
ansible_operator: 
  